"""The sheet as an object: coated before light, thinned by exposure.

The grain organ's first formulation drew each pixel's developed count
Poisson about the response curve - correct in law for any single
print, but the sheet existed only as a metaphor. This module lays
the emulsion down FIRST and lets exposure select from it, which is
what a sheet of film is:

1. COATING. Each pixel-cell holds K crystals, K ~ Poisson(lambda_K)
   with lambda_K = ceiling * A / (kappa * a) - the coating density
   Nutting demands for the process to reach its dmax at full
   development. And each crystal carries a FIXED SENSITIVITY
   THRESHOLD: the cell's K thresholds are the order statistics of K
   uniforms, generated by the exponential-spacings construction and
   quantised to 16 bits. All of it comes from the sheet stream (the
   seed) alone, before and independent of any image: same seed, same
   geometry - same crystals, whatever is later printed on them.

2. EXPOSURE. The response curve gives the fraction of crystals a
   dose renders developable: p = (1 - e^-dose)^toe, the curve read
   as the per-crystal probability it has always statistically been.

3. DEVELOPMENT. All-or-nothing and DETERMINISTIC (dossier B9/B12:
   one latent speck develops the whole crystal): a crystal develops
   iff its stored threshold lies at or below p, so the count is a
   comparison against the sheet, not a draw. More light on the same
   sheet can only develop more crystals; a saturating exposure
   prints the sheet itself; and - the reason thresholds replaced the
   organ's earlier fixed-luck quantile - the INCREMENTS between two
   exposures of one sheet now carry the thinning law's own variance,
   Var(n2 - n1) = lambda_K (p2 - p1), where the quantile coupling
   measured six-fold under-dispersed (0.44 against 2.58, the watched
   failure recorded in the tests). The marginal at any single
   exposure is Binomial(K, p) exactly, as it has been since the
   organ landed; Saunders and Selwyn never move.

THE SHEET IS STORABLE because it is data: (K, thresholds) per cell
is the film stock, `coat` makes it, `develop_on` prints against it,
and `expose` is exactly coat-then-develop - so a stock coated once,
saved, and reused is bit-identical to the throwaway path with the
same seed. A stored stock also outlives numpy: the RNG only runs at
coating, and the saved crystals are just integers. The stock's size
is the SHEET'S, not the render's: total crystals = ceiling *
sheet_area / (kappa * a), whatever pitch it is printed at.

THE HONESTY FLOOR. A cell is an independent column of emulsion, and
that is only true of a pixel at least one crystal across: below
pitch = the particle diameter, real grains would span cells and
per-pixel independence would misrepresent them. `expose` and `coat`
REFUSE pitches under the floor by name. Above it, any pitch is exact
in law - a coarse pixel is an honest aggregate of many crystals.

NUMERICAL METHODS, declared: thresholds are u16 (65536 sensitivity
levels - a 2^-16 discretisation of p, far below any observable
step); the threshold path runs whenever the realised crystal count
per cell allows (EXACT_KMAX), banded internally at a fixed band size
so the draw sequence never depends on the data; above it - hundreds
of crystals per cell and more, where a single grain is far below
anything visible - the count falls back to the normal quantile of a
fixed per-cell luck (Acklam's Phi^-1, |error| < 1.2e-9), which keeps
single-exposure law and monotone coupling but not the increment law
(a coarse aggregate has no observable increments to get wrong).
"""

import numpy as np

# the largest realised per-cell crystal count the threshold path will
# hold in a padded band; above it the normal quantile takes over
EXACT_KMAX = 192
# cells per internal band - fixed, so the sheet stream's draw order
# is a function of shape alone, never of the data
BAND = 1 << 23


def floor_um(grain_um2):
    """The particle's diameter - the least pitch an honest cell
    model can print."""
    return 2.0 * float(np.sqrt(grain_um2 / np.pi))


def _check_floor(grain_um2, pitch_um, label):
    d_min = floor_um(grain_um2)
    if pitch_um < d_min:
        raise ValueError(
            f"a {pitch_um:g} um pixel cannot hold a {label or 'process'} "
            f"crystal of {d_min:.2f} um: the cell model is honest only "
            f"at pitch >= the particle diameter - render larger, or "
            f"accept the statistical account at a coarser pitch")


def _phi_inv(v):
    """Acklam's rational approximation of the standard normal
    quantile, |relative error| < 1.15e-9 - self-contained because
    this package is pure numpy by contract."""
    a = (-3.969683028665376e+01, 2.209460984245205e+02,
         -2.759285104469687e+02, 1.383577518672690e+02,
         -3.066479806614716e+01, 2.506628277459239e+00)
    b = (-5.447609879822406e+01, 1.615858368580409e+02,
         -1.556989798598866e+02, 6.680131188771972e+01,
         -1.328068155288572e+01)
    c = (-7.784894002430293e-03, -3.223964580411365e-01,
         -2.400758277161838e+00, -2.549732539343734e+00,
         4.374664141464968e+00, 2.938163982698783e+00)
    d = (7.784695709041462e-03, 3.224671290700398e-01,
         2.445134137142996e+00, 3.754408661907416e+00)
    v = np.clip(np.asarray(v, np.float64), 1e-300, 1.0 - 1e-16)
    out = np.empty_like(v)
    lo = v < 0.02425
    hi = v > 1.0 - 0.02425
    mid = ~(lo | hi)
    if np.any(mid):
        q = v[mid] - 0.5
        r = q * q
        out[mid] = (((((a[0] * r + a[1]) * r + a[2]) * r + a[3]) * r
                     + a[4]) * r + a[5]) * q / \
                   (((((b[0] * r + b[1]) * r + b[2]) * r + b[3]) * r
                     + b[4]) * r + 1.0)
    for m, sgn in ((lo, 1.0), (hi, -1.0)):
        if not np.any(m):
            continue
        u = v[m] if sgn > 0 else 1.0 - v[m]
        q = np.sqrt(-2.0 * np.log(u))
        out[m] = sgn * (((((c[0] * q + c[1]) * q + c[2]) * q + c[3])
                         * q + c[4]) * q + c[5]) / \
            ((((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1.0)
    return out


def _band_seeds(seed, count):
    return np.random.SeedSequence(seed).spawn(count)


def _coat_band(rng, n_cells, lam_k):
    """One band of sheet: crystal counts and sorted u16 thresholds.

    The order statistics of K uniforms arrive by the exponential-
    spacings construction - K+1 iid exponentials, cumulatively
    summed and divided by the total - padded to the band's own
    realised Kmax and masked beyond each cell's K.
    """
    K = rng.poisson(lam_k, size=n_cells).astype(np.int32)
    kmax = int(K.max(initial=0))
    if kmax == 0:
        return K, np.zeros((n_cells, 0), np.uint16), kmax
    E = rng.standard_exponential((n_cells, kmax + 1), dtype=np.float32)
    C = np.cumsum(E, axis=1, dtype=np.float64)
    denom = np.take_along_axis(C, K[:, None].astype(np.intp), axis=1)
    with np.errstate(invalid="ignore", divide="ignore"):
        u = C[:, :kmax] / denom
    thr = np.minimum(u * 65536.0, 65535.0).astype(np.uint16)
    thr[np.arange(kmax)[None, :] >= K[:, None]] = np.uint16(65535)
    # a threshold of 65535 is reserved for "beyond this cell's K":
    # a real crystal quantised there still develops at p = 1 because
    # development compares against ceil(p * 65536) clipped to 65535
    # inclusively only for true crystals - handled in develop_on by
    # counting against K, never against the pad
    return K, thr, kmax


def develop_on(K, thr, p):
    """Print an exposure on a coated sheet: count, per cell (flat),
    the stored thresholds at or below the developable fraction. A
    pure comparison - development draws nothing, which is the whole
    point of a sheet."""
    pq = np.clip(np.floor(np.asarray(p, np.float64).reshape(-1)
                          * 65536.0), 0.0, 65535.0).astype(np.uint16)
    n = (thr <= pq[:, None]).sum(axis=1, dtype=np.int32)
    return np.minimum(n, K.astype(np.int32))


def coat(n_cells, ceiling, grain_um2, pitch_um, seed, label=""):
    """The film stock: lay a sheet of n_cells and return
    (K, thresholds) - reusable, savable, and bit-identical to what
    `expose` coats internally for the same seed and geometry."""
    _check_floor(grain_um2, pitch_um, label)
    area = float(pitch_um) ** 2
    lam_k = float(ceiling) * area / (_kappa() * float(grain_um2))
    if lam_k + 8.0 * np.sqrt(lam_k) + 16.0 > EXACT_KMAX:
        raise ValueError(
            f"{lam_k:.0f} crystals per cell is the aggregate regime: "
            "a stored stock would not match the normal-quantile path "
            "expose() uses there - coat at a resolved pitch, nearer "
            "the crystal")
    seeds = _band_seeds(seed, (n_cells + BAND - 1) // BAND)
    Ks, thrs, kmax = [], [], 0
    for i, s in enumerate(seeds):
        n_band = min(BAND, n_cells - i * BAND)
        K, thr, km = _coat_band(np.random.default_rng(s), n_band, lam_k)
        Ks.append(K)
        thrs.append(thr)
        kmax = max(kmax, km)
    thrs = [np.pad(t, ((0, 0), (0, kmax - t.shape[1])),
                   constant_values=np.uint16(65535)) for t in thrs]
    return np.concatenate(Ks), np.vstack(thrs)


def _kappa():
    from atlas_film.processes import KAPPA
    return KAPPA


def expose(p, ceiling, grain_um2, pitch_um, seed, label=""):
    """Coat a sheet, expose it to the developable-fraction field p,
    and return the developed crystal count per cell - band by band,
    the band size fixed so the sheet is a function of (seed, shape)
    alone. Identical to coat() + develop_on() with the same seed."""
    _check_floor(grain_um2, pitch_um, label)
    area = float(pitch_um) ** 2
    lam_k = float(ceiling) * area / (_kappa() * float(grain_um2))
    flat = p.reshape(-1)
    n = np.empty(flat.shape[0], np.int32)
    seeds = _band_seeds(seed, (flat.shape[0] + BAND - 1) // BAND)
    for i, s in enumerate(seeds):
        lo, hi = i * BAND, min((i + 1) * BAND, flat.shape[0])
        rng = np.random.default_rng(s)
        if lam_k + 8.0 * np.sqrt(lam_k) + 16.0 <= EXACT_KMAX:
            K, thr, _ = _coat_band(rng, hi - lo, lam_k)
            n[lo:hi] = develop_on(K, thr, flat[lo:hi])
        else:
            # the aggregate regime: hundreds of crystals per cell and
            # up. Single-exposure law and monotone coupling kept via
            # the normal quantile of fixed per-cell luck; the
            # increment law is declared out of scope here, where one
            # grain is far below anything a print resolves.
            K = rng.poisson(lam_k, size=hi - lo)
            v = rng.random(hi - lo)
            q = np.clip(flat[lo:hi].astype(np.float64), 0.0, 1.0)
            mu = K * q
            sig = np.sqrt(np.maximum(mu * (1.0 - q), 0.0))
            n[lo:hi] = np.clip(np.rint(mu + sig * _phi_inv(v)), 0, K)
    return n.reshape(p.shape)
